# DB setting
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/jpatest?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
    username: root
    password: 1234

# DB logging
logging:
  level:
    org.springframework.jdbc: debug
    # HTTP request message 로그로 출력
    org.apache.coyote.http11: debug
    com.mybatis.board.repository: trace

# jsessionid url 에 붙는것 삭제
server:
  servlet:
    session:
      tracking-modes: cookie

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

# MyBatis settings
mybatis:
# XML 에서 Domain 의 클래스를 클래스명으로만 사용 가능하도록 설정 (미설정 시 패키지명까지 모두 작성 필수)
# type-aliases-package: com.mybatis.board.domain

file:
  # imgs: C:/gangsa/imgs/