# DB setting
spring:
  datasource:
    url: jdbc:mysql://ls-bf77c64060196e6d230cdf2d53222ad0bb35b75d.clmym0ek09ts.ap-northeast-2.rds.amazonaws.com:3306/culendar?useUnicode=true&characterEncoding=UTF-8&characterSetResult=UTF-8&useSSL=true
    username: culendar
    password: culendarpassword
    devtools:
      # Auto Restart
      restart:
        enabled: true
        additional-exclude: static/**,public/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    session:
      tracking-modes: cookie